# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Fixed client tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Run fixed client tests 
      run: ./src/fixedClientEnvironmentTest/resources/run-fixed-client-environment-test.sh
      shell: bash

    - name: Generate test reports
      run: ./gradlew jacocoFixedClientEnvironmentTestReport

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        env_vars: OS,JDK
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        files: ./build/reports/jacoco/jacocoFixedClientEnvironmentTestReport/jacocoFixedClientEnvironmentTestReport.xml
        flags: fixedclientenvironment
        name: codecov-umbrella
        verbose: true
      env:
        OS: linux
        JDK: openjdk11

    - name: Upload to sonarcube
      run: ./gradlew sonarqube --info
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        OS: linux
        JDK: openjdk11
