# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Fixed client tests

on:
  push:
    branches: [ ci_iss680 ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build code
      run: ./gradlew assemble

    - name: Run fixed client tests 
      run: ./src/fixedClientEnvironmentTest/resources/run-fixed-client-environment-test.sh
      shell: bash

    - name: Generate test reports and upload them
      run: | 
        ./gradlew jacocoFixedClientEnvironmentTestReport
        bash <(curl -s https://codecov.io/bash) -e JDK,OS -F fixedclientenvironment -f build/reports/jacoco/jacocoFixedClientEnvironmentTestReport/jacocoFixedClientEnvironmentTestReport.xml
      env: 
        OS: linux
        JDK: openjdk11

