# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Integration tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Run integration tests 
      run: ./gradlew integrationTest

    - name: Generate test reports
      run: ./gradlew jacocoIntegrationTestReport 

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        env_vars: OS,JDK
        fail_ci_if_error: true
        files: ./build/reports/jacoco/jacocoIntegrationTestReport/jacocoIntegrationTestReport.xml
        flags: integration
        name: codecov-umbrella
        verbose: true
      env:
        OS: linux
        JDK: openjdk11

#    - name: Generate test reports and upload to codecov
#      run: | 
#        ./gradlew jacocoIntegrationTestReport 
#        bash <(curl -s https://codecov.io/bash) -e JDK,OS -F integration -f build/reports/jacoco/jacocoIntegrationTestReport/jacocoIntegrationTestReport.xml
#      env: 
#        OS: linux
#        JDK: openjdk11

