name: RunFairSECO

on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    RunFairSECO:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: tortellini-tools/action@v3
            - uses: actions/upload-artifact@v3
              with:
                  name: tortellini-result
                  path: .tortellini/out
            - uses: anchore/sbom-action@v0
              with:
                  artifact-name: SBOM.spdx # Output is in JSON format
            - uses: actions/checkout@v3
              with:
                repository: QDUNI/FairSECO
                path: FAIRSECO_Assets
                ref: 'NBF-239-Test-External-Repos'
            - uses: QDUNI/FairSECO@NBF-239-Test-External-Repos
              with:
                  myToken: ${{ secrets.GITHUB_TOKEN }}
            - uses: actions/upload-artifact@v3
              with:
                  name: FairSECO Result
                  path: .FAIRSECO/
